services:
  backend:
    container_name: backend
    build: ./src/backend/.
    ports:
      - "3000:3000"
    volumes:
      - transcendence_db:/app/database
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/database/database.db
    restart: unless-stopped
    networks:
      - transcendence

  frontend:
    build: ./src/frontend/.  # Uses Dockerfile (nginx)
    container_name: frontend
    ports:
      - "443:443"  # HTTPS
    networks:
      - transcendence
    restart: unless-stopped

volumes:
  transcendence_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: src/database/

networks:
  transcendence:
    driver: bridge