services:
  backend:
    container_name: backend
    build: ./backend/.
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - transcendence_db:/app/database
    environment:
      - NODE_ENV=development
      - FORCE_COLOR=1
      - DATABASE_PATH=/app/database/database.db
    tty: true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VITE_BACKEND_URL=http://host.docker.internal:3000

volumes:
  transcendence_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: database/

